version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_VeVdigital
    restart: unless-stopped
    environment:
      POSTGRES_USER: burddan
      POSTGRES_PASSWORD: burddan
      POSTGRES_DB: vovodigital
    ports:
      - "5432:5432"
    volumes:
      - ./sql_scripts:/var/lib/postgresql/data

